name: CD

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write   # Workload Identity Federation

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # إضافة متغير البيئة DATABASE_URL
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      # تشغيل الميجرشنز بعد بناء الصورة وقبل النشر
      - name: Run DB migrations
        run: npm run db:migrate

      # تسجيل الدخول إلى GCP باستخدام Workload Identity Federation
      - id: 'auth-gcp'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/710615474249/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'cloud-run-deployer@total-triumph-490016-f8.iam.gserviceaccount.com'

      # إعداد gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: 'total-triumph-490016-f8'

      # بناء Docker image ودفعه إلى Artifact Registry
      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/total-triumph-490016-f8/notely-ar-repo/notely:latest .

      # نشر التحديث على Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/total-triumph-490016-f8/notely-ar-repo/notely:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project total-triumph-490016-f8 \
            --max-instances=4